{ ... }:
{
  # This file is dynamically generated by the installer.
  # Values here are stubs for the ISO build.
  networking.hostName = "cakeos";
  
  # User settings
  # Note: These will be overridden by the installer.
  users.users.majo = {
    initialHashedPassword = ""; # Stub
  };
  
  # Root settings
  users.users.root.initialHashedPassword = ""; # Stub

  # RAM disks
  fileSystems = {};
}
